// Default 221-color set for all users
// Each user gets initialized with this set at quantity 0

export const defaultColors = [
  // ZG Family (1-8)
  { code: 'ZG1', name: 'ZG1', hexColor: '#DAABB3', family: 'ZG' },
  { code: 'ZG2', name: 'ZG2', hexColor: '#D6AA87', family: 'ZG' },
  { code: 'ZG3', name: 'ZG3', hexColor: '#C1BD8D', family: 'ZG' },
  { code: 'ZG4', name: 'ZG4', hexColor: '#96B69F', family: 'ZG' },
  { code: 'ZG5', name: 'ZG5', hexColor: '#849DC6', family: 'ZG' },
  { code: 'ZG6', name: 'ZG6', hexColor: '#94BFE2', family: 'ZG' },
  { code: 'ZG7', name: 'ZG7', hexColor: '#E2A9D2', family: 'ZG' },
  { code: 'ZG8', name: 'ZG8', hexColor: '#AB91C0', family: 'ZG' },

  // A Family (1-26)
  { code: 'A1', name: 'A1', hexColor: '#FAF4C8', family: 'A' },
  { code: 'A2', name: 'A2', hexColor: '#FFFFD5', family: 'A' },
  { code: 'A3', name: 'A3', hexColor: '#FEFF8B', family: 'A' },
  { code: 'A4', name: 'A4', hexColor: '#FBED56', family: 'A' },
  { code: 'A5', name: 'A5', hexColor: '#F4D738', family: 'A' },
  { code: 'A6', name: 'A6', hexColor: '#FEAC4C', family: 'A' },
  { code: 'A7', name: 'A7', hexColor: '#FE8B4C', family: 'A' },
  { code: 'A8', name: 'A8', hexColor: '#FFDA45', family: 'A' },
  { code: 'A9', name: 'A9', hexColor: '#FF995B', family: 'A' },
  { code: 'A10', name: 'A10', hexColor: '#F77C31', family: 'A' },
  { code: 'A11', name: 'A11', hexColor: '#FFDD99', family: 'A' },
  { code: 'A12', name: 'A12', hexColor: '#FE9F72', family: 'A' },
  { code: 'A13', name: 'A13', hexColor: '#FFC365', family: 'A' },
  { code: 'A14', name: 'A14', hexColor: '#FD543D', family: 'A' },
  { code: 'A15', name: 'A15', hexColor: '#FFF365', family: 'A' },
  { code: 'A16', name: 'A16', hexColor: '#FFFF9F', family: 'A' },
  { code: 'A17', name: 'A17', hexColor: '#FFE36E', family: 'A' },
  { code: 'A18', name: 'A18', hexColor: '#FEBE7D', family: 'A' },
  { code: 'A19', name: 'A19', hexColor: '#FD7C72', family: 'A' },
  { code: 'A20', name: 'A20', hexColor: '#FFD568', family: 'A' },
  { code: 'A21', name: 'A21', hexColor: '#FFE395', family: 'A' },
  { code: 'A22', name: 'A22', hexColor: '#F4F57D', family: 'A' },
  { code: 'A23', name: 'A23', hexColor: '#E6C9B7', family: 'A' },
  { code: 'A24', name: 'A24', hexColor: '#F7F8A2', family: 'A' },
  { code: 'A25', name: 'A25', hexColor: '#FFD67D', family: 'A' },
  { code: 'A26', name: 'A26', hexColor: '#FFC830', family: 'A' },

  // B Family (1-32)
  { code: 'B1', name: 'B1', hexColor: '#E6EE31', family: 'B' },
  { code: 'B2', name: 'B2', hexColor: '#63F347', family: 'B' },
  { code: 'B3', name: 'B3', hexColor: '#9EF780', family: 'B' },
  { code: 'B4', name: 'B4', hexColor: '#5DE035', family: 'B' },
  { code: 'B5', name: 'B5', hexColor: '#35E352', family: 'B' },
  { code: 'B6', name: 'B6', hexColor: '#65E2A6', family: 'B' },
  { code: 'B7', name: 'B7', hexColor: '#3DAF80', family: 'B' },
  { code: 'B8', name: 'B8', hexColor: '#1C9C4F', family: 'B' },
  { code: 'B9', name: 'B9', hexColor: '#27523A', family: 'B' },
  { code: 'B10', name: 'B10', hexColor: '#95D3C2', family: 'B' },
  { code: 'B11', name: 'B11', hexColor: '#5D722A', family: 'B' },
  { code: 'B12', name: 'B12', hexColor: '#166F41', family: 'B' },
  { code: 'B13', name: 'B13', hexColor: '#CAEB7B', family: 'B' },
  { code: 'B14', name: 'B14', hexColor: '#ADE946', family: 'B' },
  { code: 'B15', name: 'B15', hexColor: '#2E5132', family: 'B' },
  { code: 'B16', name: 'B16', hexColor: '#C5ED9C', family: 'B' },
  { code: 'B17', name: 'B17', hexColor: '#9BB13A', family: 'B' },
  { code: 'B18', name: 'B18', hexColor: '#E6EE49', family: 'B' },
  { code: 'B19', name: 'B19', hexColor: '#24B88C', family: 'B' },
  { code: 'B20', name: 'B20', hexColor: '#C2F0CC', family: 'B' },
  { code: 'B21', name: 'B21', hexColor: '#156A6B', family: 'B' },
  { code: 'B22', name: 'B22', hexColor: '#0B3C43', family: 'B' },
  { code: 'B23', name: 'B23', hexColor: '#303A21', family: 'B' },
  { code: 'B24', name: 'B24', hexColor: '#EEFCA5', family: 'B' },
  { code: 'B25', name: 'B25', hexColor: '#4E846D', family: 'B' },
  { code: 'B26', name: 'B26', hexColor: '#8D7A35', family: 'B' },
  { code: 'B27', name: 'B27', hexColor: '#CCE1AF', family: 'B' },
  { code: 'B28', name: 'B28', hexColor: '#9EE5B9', family: 'B' },
  { code: 'B29', name: 'B29', hexColor: '#C5E254', family: 'B' },
  { code: 'B30', name: 'B30', hexColor: '#E2FCB1', family: 'B' },
  { code: 'B31', name: 'B31', hexColor: '#B0E792', family: 'B' },
  { code: 'B32', name: 'B32', hexColor: '#9CAB5A', family: 'B' },

  // C Family (1-29)
  { code: 'C1', name: 'C1', hexColor: '#E8FFE7', family: 'C' },
  { code: 'C2', name: 'C2', hexColor: '#A9F9FC', family: 'C' },
  { code: 'C3', name: 'C3', hexColor: '#A0E2FB', family: 'C' },
  { code: 'C4', name: 'C4', hexColor: '#41CCFF', family: 'C' },
  { code: 'C5', name: 'C5', hexColor: '#01ACEB', family: 'C' },
  { code: 'C6', name: 'C6', hexColor: '#50AAF0', family: 'C' },
  { code: 'C7', name: 'C7', hexColor: '#3677D2', family: 'C' },
  { code: 'C8', name: 'C8', hexColor: '#0F54C0', family: 'C' },
  { code: 'C9', name: 'C9', hexColor: '#324BCA', family: 'C' },
  { code: 'C10', name: 'C10', hexColor: '#3EBCE2', family: 'C' },
  { code: 'C11', name: 'C11', hexColor: '#28DDDE', family: 'C' },
  { code: 'C12', name: 'C12', hexColor: '#1C334D', family: 'C' },
  { code: 'C13', name: 'C13', hexColor: '#CDE8FF', family: 'C' },
  { code: 'C14', name: 'C14', hexColor: '#D5FDFF', family: 'C' },
  { code: 'C15', name: 'C15', hexColor: '#22C4C6', family: 'C' },
  { code: 'C16', name: 'C16', hexColor: '#1557A8', family: 'C' },
  { code: 'C17', name: 'C17', hexColor: '#04D1F6', family: 'C' },
  { code: 'C18', name: 'C18', hexColor: '#1D3344', family: 'C' },
  { code: 'C19', name: 'C19', hexColor: '#1887A2', family: 'C' },
  { code: 'C20', name: 'C20', hexColor: '#176DAF', family: 'C' },
  { code: 'C21', name: 'C21', hexColor: '#BEDDFF', family: 'C' },
  { code: 'C22', name: 'C22', hexColor: '#67B4BE', family: 'C' },
  { code: 'C23', name: 'C23', hexColor: '#C8E2FF', family: 'C' },
  { code: 'C24', name: 'C24', hexColor: '#7CC4FF', family: 'C' },
  { code: 'C25', name: 'C25', hexColor: '#A9E5E5', family: 'C' },
  { code: 'C26', name: 'C26', hexColor: '#3CAED8', family: 'C' },
  { code: 'C27', name: 'C27', hexColor: '#D3DFFA', family: 'C' },
  { code: 'C28', name: 'C28', hexColor: '#BBCFED', family: 'C' },
  { code: 'C29', name: 'C29', hexColor: '#34488E', family: 'C' },

  // D Family (1-26)
  { code: 'D1', name: 'D1', hexColor: '#AEB4F2', family: 'D' },
  { code: 'D2', name: 'D2', hexColor: '#858EDD', family: 'D' },
  { code: 'D3', name: 'D3', hexColor: '#2F54AF', family: 'D' },
  { code: 'D4', name: 'D4', hexColor: '#182A84', family: 'D' },
  { code: 'D5', name: 'D5', hexColor: '#B843C5', family: 'D' },
  { code: 'D6', name: 'D6', hexColor: '#AC7BDE', family: 'D' },
  { code: 'D7', name: 'D7', hexColor: '#8854B3', family: 'D' },
  { code: 'D8', name: 'D8', hexColor: '#E2D3FF', family: 'D' },
  { code: 'D9', name: 'D9', hexColor: '#D5B9F8', family: 'D' },
  { code: 'D10', name: 'D10', hexColor: '#361B51', family: 'D' },
  { code: 'D11', name: 'D11', hexColor: '#B9BAE1', family: 'D' },
  { code: 'D12', name: 'D12', hexColor: '#DE9AD4', family: 'D' },
  { code: 'D13', name: 'D13', hexColor: '#B90095', family: 'D' },
  { code: 'D14', name: 'D14', hexColor: '#8B279B', family: 'D' },
  { code: 'D15', name: 'D15', hexColor: '#2F1F90', family: 'D' },
  { code: 'D16', name: 'D16', hexColor: '#E3E1EE', family: 'D' },
  { code: 'D17', name: 'D17', hexColor: '#C4D4F6', family: 'D' },
  { code: 'D18', name: 'D18', hexColor: '#A45EC7', family: 'D' },
  { code: 'D19', name: 'D19', hexColor: '#D8C3D7', family: 'D' },
  { code: 'D20', name: 'D20', hexColor: '#9C32B2', family: 'D' },
  { code: 'D21', name: 'D21', hexColor: '#9A009B', family: 'D' },
  { code: 'D22', name: 'D22', hexColor: '#333A95', family: 'D' },
  { code: 'D23', name: 'D23', hexColor: '#EBDAFC', family: 'D' },
  { code: 'D24', name: 'D24', hexColor: '#7786E5', family: 'D' },
  { code: 'D25', name: 'D25', hexColor: '#494FC7', family: 'D' },
  { code: 'D26', name: 'D26', hexColor: '#DFC2F8', family: 'D' },

  // E Family (1-24)
  { code: 'E1', name: 'E1', hexColor: '#FDD3CC', family: 'E' },
  { code: 'E2', name: 'E2', hexColor: '#FEC0DF', family: 'E' },
  { code: 'E3', name: 'E3', hexColor: '#FFB7E7', family: 'E' },
  { code: 'E4', name: 'E4', hexColor: '#E8649E', family: 'E' },
  { code: 'E5', name: 'E5', hexColor: '#F551A2', family: 'E' },
  { code: 'E6', name: 'E6', hexColor: '#F13D74', family: 'E' },
  { code: 'E7', name: 'E7', hexColor: '#C63478', family: 'E' },
  { code: 'E8', name: 'E8', hexColor: '#FFDBE9', family: 'E' },
  { code: 'E9', name: 'E9', hexColor: '#E970CC', family: 'E' },
  { code: 'E10', name: 'E10', hexColor: '#D33793', family: 'E' },
  { code: 'E11', name: 'E11', hexColor: '#FCDDD2', family: 'E' },
  { code: 'E12', name: 'E12', hexColor: '#F78FC3', family: 'E' },
  { code: 'E13', name: 'E13', hexColor: '#B5006D', family: 'E' },
  { code: 'E14', name: 'E14', hexColor: '#FFD1BA', family: 'E' },
  { code: 'E15', name: 'E15', hexColor: '#F8C7C9', family: 'E' },
  { code: 'E16', name: 'E16', hexColor: '#FFF3EB', family: 'E' },
  { code: 'E17', name: 'E17', hexColor: '#FFE2EA', family: 'E' },
  { code: 'E18', name: 'E18', hexColor: '#FFC7DB', family: 'E' },
  { code: 'E19', name: 'E19', hexColor: '#FEBAD5', family: 'E' },
  { code: 'E20', name: 'E20', hexColor: '#D8C7D1', family: 'E' },
  { code: 'E21', name: 'E21', hexColor: '#BD9DA1', family: 'E' },
  { code: 'E22', name: 'E22', hexColor: '#B785A1', family: 'E' },
  { code: 'E23', name: 'E23', hexColor: '#937A8D', family: 'E' },
  { code: 'E24', name: 'E24', hexColor: '#E1BCE8', family: 'E' },

  // F Family (1-25)
  { code: 'F1', name: 'F1', hexColor: '#FD957B', family: 'F' },
  { code: 'F2', name: 'F2', hexColor: '#FC3D46', family: 'F' },
  { code: 'F3', name: 'F3', hexColor: '#F74941', family: 'F' },
  { code: 'F4', name: 'F4', hexColor: '#FC283C', family: 'F' },
  { code: 'F5', name: 'F5', hexColor: '#E7002F', family: 'F' },
  { code: 'F6', name: 'F6', hexColor: '#943630', family: 'F' },
  { code: 'F7', name: 'F7', hexColor: '#971937', family: 'F' },
  { code: 'F8', name: 'F8', hexColor: '#BC0028', family: 'F' },
  { code: 'F9', name: 'F9', hexColor: '#E2677A', family: 'F' },
  { code: 'F10', name: 'F10', hexColor: '#8A4526', family: 'F' },
  { code: 'F11', name: 'F11', hexColor: '#5A2121', family: 'F' },
  { code: 'F12', name: 'F12', hexColor: '#FD4E6A', family: 'F' },
  { code: 'F13', name: 'F13', hexColor: '#F35744', family: 'F' },
  { code: 'F14', name: 'F14', hexColor: '#FFA9AD', family: 'F' },
  { code: 'F15', name: 'F15', hexColor: '#D30022', family: 'F' },
  { code: 'F16', name: 'F16', hexColor: '#FEC2A6', family: 'F' },
  { code: 'F17', name: 'F17', hexColor: '#E69C79', family: 'F' },
  { code: 'F18', name: 'F18', hexColor: '#D37C46', family: 'F' },
  { code: 'F19', name: 'F19', hexColor: '#C1444A', family: 'F' },
  { code: 'F20', name: 'F20', hexColor: '#CD9391', family: 'F' },
  { code: 'F21', name: 'F21', hexColor: '#F7B4C6', family: 'F' },
  { code: 'F22', name: 'F22', hexColor: '#FDC0D0', family: 'F' },
  { code: 'F23', name: 'F23', hexColor: '#F67E66', family: 'F' },
  { code: 'F24', name: 'F24', hexColor: '#E698AA', family: 'F' },
  { code: 'F25', name: 'F25', hexColor: '#E54B4F', family: 'F' },

  // G Family (1-21)
  { code: 'G1', name: 'G1', hexColor: '#FFE2CE', family: 'G' },
  { code: 'G2', name: 'G2', hexColor: '#FFC4AA', family: 'G' },
  { code: 'G3', name: 'G3', hexColor: '#F4C3A5', family: 'G' },
  { code: 'G4', name: 'G4', hexColor: '#E1B383', family: 'G' },
  { code: 'G5', name: 'G5', hexColor: '#EDB045', family: 'G' },
  { code: 'G6', name: 'G6', hexColor: '#E99C17', family: 'G' },
  { code: 'G7', name: 'G7', hexColor: '#9D5B3E', family: 'G' },
  { code: 'G8', name: 'G8', hexColor: '#753B32', family: 'G' },
  { code: 'G9', name: 'G9', hexColor: '#E6B483', family: 'G' },
  { code: 'G10', name: 'G10', hexColor: '#D98C39', family: 'G' },
  { code: 'G11', name: 'G11', hexColor: '#E0C593', family: 'G' },
  { code: 'G12', name: 'G12', hexColor: '#FFC890', family: 'G' },
  { code: 'G13', name: 'G13', hexColor: '#B7714A', family: 'G' },
  { code: 'G14', name: 'G14', hexColor: '#8D614C', family: 'G' },
  { code: 'G15', name: 'G15', hexColor: '#FCF9E0', family: 'G' },
  { code: 'G16', name: 'G16', hexColor: '#F2D9BA', family: 'G' },
  { code: 'G17', name: 'G17', hexColor: '#7B524B', family: 'G' },
  { code: 'G18', name: 'G18', hexColor: '#FFE4CC', family: 'G' },
  { code: 'G19', name: 'G19', hexColor: '#E07935', family: 'G' },
  { code: 'G20', name: 'G20', hexColor: '#A94023', family: 'G' },
  { code: 'G21', name: 'G21', hexColor: '#B88558', family: 'G' },

  // H Family (1-23)
  { code: 'H1透明', name: 'H1 透明', hexColor: '#FDFBFF', family: 'H' },
  { code: 'H2白色', name: 'H2 白色', hexColor: '#FFFFFF', family: 'H' },
  { code: 'H3', name: 'H3', hexColor: '#B6B1BA', family: 'H' },
  { code: 'H4', name: 'H4', hexColor: '#89858C', family: 'H' },
  { code: 'H5', name: 'H5', hexColor: '#48464E', family: 'H' },
  { code: 'H6', name: 'H6', hexColor: '#2F2B2F', family: 'H' },
  { code: 'H7黑色', name: 'H7 黑色', hexColor: '#000000', family: 'H' },
  { code: 'H8', name: 'H8', hexColor: '#E7D6DB', family: 'H' },
  { code: 'H9', name: 'H9', hexColor: '#EDEDED', family: 'H' },
  { code: 'H10', name: 'H10', hexColor: '#EEE9EA', family: 'H' },
  { code: 'H11', name: 'H11', hexColor: '#CECDD5', family: 'H' },
  { code: 'H12', name: 'H12', hexColor: '#FFF5ED', family: 'H' },
  { code: 'H13', name: 'H13', hexColor: '#F5ECD2', family: 'H' },
  { code: 'H14', name: 'H14', hexColor: '#CFD7D3', family: 'H' },
  { code: 'H15', name: 'H15', hexColor: '#98A6A8', family: 'H' },
  { code: 'H16', name: 'H16', hexColor: '#1D1414', family: 'H' },
  { code: 'H17', name: 'H17', hexColor: '#F1EDED', family: 'H' },
  { code: 'H18', name: 'H18', hexColor: '#FFFDF0', family: 'H' },
  { code: 'H19', name: 'H19', hexColor: '#F6EFE2', family: 'H' },
  { code: 'H20', name: 'H20', hexColor: '#949FA3', family: 'H' },
  { code: 'H21', name: 'H21', hexColor: '#FFFBE1', family: 'H' },
  { code: 'H22', name: 'H22', hexColor: '#CACAD4', family: 'H' },
  { code: 'H23', name: 'H23', hexColor: '#9A9D94', family: 'H' },

  // M Family (1-15)
  { code: 'M1', name: 'M1', hexColor: '#BCC6B8', family: 'M' },
  { code: 'M2', name: 'M2', hexColor: '#8AA386', family: 'M' },
  { code: 'M3', name: 'M3', hexColor: '#697D80', family: 'M' },
  { code: 'M4', name: 'M4', hexColor: '#E3D2BC', family: 'M' },
  { code: 'M5', name: 'M5', hexColor: '#D0CCAA', family: 'M' },
  { code: 'M6', name: 'M6', hexColor: '#B0A782', family: 'M' },
  { code: 'M7', name: 'M7', hexColor: '#B4A497', family: 'M' },
  { code: 'M8', name: 'M8', hexColor: '#B38281', family: 'M' },
  { code: 'M9', name: 'M9', hexColor: '#A58767', family: 'M' },
  { code: 'M10', name: 'M10', hexColor: '#C5B2BC', family: 'M' },
  { code: 'M11', name: 'M11', hexColor: '#9F7594', family: 'M' },
  { code: 'M12', name: 'M12', hexColor: '#644749', family: 'M' },
  { code: 'M13', name: 'M13', hexColor: '#D19066', family: 'M' },
  { code: 'M14', name: 'M14', hexColor: '#C77362', family: 'M' },
  { code: 'M15', name: 'M15', hexColor: '#757D7B', family: 'M' },

  // P Family (1-23)
  { code: 'P1', name: 'P1', hexColor: '#FCF7F8', family: 'P' },
  { code: 'P2', name: 'P2', hexColor: '#B0A9AC', family: 'P' },
  { code: 'P3', name: 'P3', hexColor: '#AFDCAB', family: 'P' },
  { code: 'P4', name: 'P4', hexColor: '#FEA49F', family: 'P' },
  { code: 'P5', name: 'P5', hexColor: '#EE8C3E', family: 'P' },
  { code: 'P6', name: 'P6', hexColor: '#5FD0A7', family: 'P' },
  { code: 'P7', name: 'P7', hexColor: '#EB9270', family: 'P' },
  { code: 'P8', name: 'P8', hexColor: '#F0D958', family: 'P' },
  { code: 'P9', name: 'P9', hexColor: '#D9D9D9', family: 'P' },
  { code: 'P10', name: 'P10', hexColor: '#D9C7EA', family: 'P' },
  { code: 'P11', name: 'P11', hexColor: '#F3ECC9', family: 'P' },
  { code: 'P12', name: 'P12', hexColor: '#E6EEF2', family: 'P' },
  { code: 'P13', name: 'P13', hexColor: '#AACBEF', family: 'P' },
  { code: 'P14', name: 'P14', hexColor: '#3376B0', family: 'P' },
  { code: 'P15', name: 'P15', hexColor: '#668575', family: 'P' },
  { code: 'P16', name: 'P16', hexColor: '#FEBF45', family: 'P' },
  { code: 'P17', name: 'P17', hexColor: '#FEA324', family: 'P' },
  { code: 'P18', name: 'P18', hexColor: '#FEB89F', family: 'P' },
  { code: 'P19', name: 'P19', hexColor: '#FFE0E9', family: 'P' },
  { code: 'P20', name: 'P20', hexColor: '#FEBECF', family: 'P' },
  { code: 'P21', name: 'P21', hexColor: '#ECBEBF', family: 'P' },
  { code: 'P22', name: 'P22', hexColor: '#E4A89F', family: 'P' },
  { code: 'P23', name: 'P23', hexColor: '#A56268', family: 'P' },

  // Q Family (1-5)
  { code: 'Q1', name: 'Q1', hexColor: '#F2A5E8', family: 'Q' },
  { code: 'Q2', name: 'Q2', hexColor: '#E9EC91', family: 'Q' },
  { code: 'Q3', name: 'Q3', hexColor: '#FFFF00', family: 'Q' },
  { code: 'Q4', name: 'Q4', hexColor: '#FFEBFA', family: 'Q' },
  { code: 'Q5', name: 'Q5', hexColor: '#76CEDE', family: 'Q' },

  // R Family (1-28)
  { code: 'R1', name: 'R1', hexColor: '#D50D21', family: 'R' },
  { code: 'R2', name: 'R2', hexColor: '#F92F83', family: 'R' },
  { code: 'R3', name: 'R3', hexColor: '#FD8324', family: 'R' },
  { code: 'R4', name: 'R4', hexColor: '#F8EC31', family: 'R' },
  { code: 'R5', name: 'R5', hexColor: '#35C75B', family: 'R' },
  { code: 'R6', name: 'R6', hexColor: '#23B891', family: 'R' },
  { code: 'R7', name: 'R7', hexColor: '#19779D', family: 'R' },
  { code: 'R8', name: 'R8', hexColor: '#1A60C3', family: 'R' },
  { code: 'R9', name: 'R9', hexColor: '#9A56B4', family: 'R' },
  { code: 'R10', name: 'R10', hexColor: '#FFDB4C', family: 'R' },
  { code: 'R11', name: 'R11', hexColor: '#FFEBFA', family: 'R' },
  { code: 'R12', name: 'R12', hexColor: '#D8D5CE', family: 'R' },
  { code: 'R13', name: 'R13', hexColor: '#55514C', family: 'R' },
  { code: 'R14', name: 'R14', hexColor: '#9FE4DF', family: 'R' },
  { code: 'R15', name: 'R15', hexColor: '#77CEE9', family: 'R' },
  { code: 'R16', name: 'R16', hexColor: '#3ECFCA', family: 'R' },
  { code: 'R17', name: 'R17', hexColor: '#4A867A', family: 'R' },
  { code: 'R18', name: 'R18', hexColor: '#7FCD9D', family: 'R' },
  { code: 'R19', name: 'R19', hexColor: '#CDE55D', family: 'R' },
  { code: 'R20', name: 'R20', hexColor: '#E8C7B4', family: 'R' },
  { code: 'R21', name: 'R21', hexColor: '#AD6F3C', family: 'R' },
  { code: 'R22', name: 'R22', hexColor: '#6C372F', family: 'R' },
  { code: 'R23', name: 'R23', hexColor: '#FEB872', family: 'R' },
  { code: 'R24', name: 'R24', hexColor: '#F3C1C0', family: 'R' },
  { code: 'R25', name: 'R25', hexColor: '#C9675E', family: 'R' },
  { code: 'R26', name: 'R26', hexColor: '#D293BE', family: 'R' },
  { code: 'R27', name: 'R27', hexColor: '#EA8CB1', family: 'R' },
  { code: 'R28', name: 'R28', hexColor: '#9C87D6', family: 'R' },

  // T Family (1)
  { code: 'T1', name: 'T1', hexColor: '#FFFFFF', family: 'T' },

  // Y Family (1-5)
  { code: 'Y1', name: 'Y1', hexColor: '#FD6FB4', family: 'Y' },
  { code: 'Y2', name: 'Y2', hexColor: '#FEB481', family: 'Y' },
  { code: 'Y3', name: 'Y3', hexColor: '#D7FAA0', family: 'Y' },
  { code: 'Y4', name: 'Y4', hexColor: '#8BDBFA', family: 'Y' },
  { code: 'Y5', name: 'Y5', hexColor: '#E987EA', family: 'Y' },
] as const;

// Extract unique families for UI
export const colorFamilies = Array.from(new Set(defaultColors.map(c => c.family)));
